spring:
  application:
    name: mseureka

server:
  port: 31001

eureka:
  instance:
    hostname: mseureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://mseureka2:31002/eureka/
#  server:
#    enable-self-preservation: true \u81EA\u6211\u4FDD\u62A4\u673A\u5236



