server:
  port: 32002


spring:
  application:
    name: consumer002_feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://mseureka2:31002/eureka/,http://mseureka1:31001/eureka/
  instance:
    prefer-ip-address: true
