spring:
  application:
    name: mseureka
server:
  port: 31002

eureka:
  instance:
    hostname: mseureka2
    instance-id: mseureka2_31002
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://mseureka1:31001/eureka/

